LANGS = ("uz", "ru", "en")

TEXTS: dict[str, dict[str, str]] = {
    "uz": {
        "choose_lang": "Tilni tanlang / Выберите язык / Choose a language",
        "welcome": "Assalomu alaykum, {name}! Tur tanlash va bron qilish uchun menyudan foydalaning yoki shunchaki savol yozing.",
        "btn_tours": "🌍 Turlar",
        "btn_my_bookings": "📋 Bronlarim",
        "btn_contacts": "📞 Aloqa",
        "btn_lang": "🌐 Til",
        "btn_book": "✅ Bron qilish",
        "btn_back": "⬅️ Orqaga",
        "btn_send_phone": "📱 Raqamni yuborish",
        "btn_confirm": "✅ Tasdiqlash",
        "btn_cancel": "❌ Bekor qilish",
        "no_tours": "Hozircha faol turlar yo'q.",
        "tours_title": "Mavjud turlar:",
        "tour_card": "<b>{title}</b>\n\n{description}\n\n💵 Narxi: {price} {currency}\n📅 Sana: {date}\n🪑 Bo'sh joylar: {free}",
        "date_tbd": "kelishiladi",
        "tour_not_found": "Tur topilmadi.",
        "no_seats": "Kechirasiz, bu turda bo'sh joy qolmadi.",
        "ask_people": "Necha kishi borasiz? (1 dan {max} gacha raqam yozing)",
        "bad_people": "Iltimos, 1 dan {max} gacha raqam yozing.",
        "ask_phone": "Telefon raqamingizni yuboring (tugma orqali yoki +998XXXXXXXXX ko'rinishida).",
        "bad_phone": "Raqam noto'g'ri. Masalan: +998901234567",
        "confirm_booking": "Tekshiring:\n\n🌍 {title}\n👥 {people} kishi\n📱 {phone}\n💵 Jami: {total} {currency}\n\nTasdiqlaysizmi?",
        "booking_sent": "Rahmat! So'rovingiz #{id} qabul qilindi. Menejer tez orada bog'lanadi.",
        "booking_cancelled": "Bron bekor qilindi.",
        "booking_confirmed_user": "✅ #{id} bronningiz tasdiqlandi: {title}",
        "booking_rejected_user": "❌ #{id} bronningiz rad etildi: {title}. Savollar bo'lsa, biz bilan bog'laning.",
        "no_bookings": "Sizda hali bron yo'q.",
        "my_bookings_title": "Sizning bronlaringiz:",
        "status_pending": "⏳ kutilmoqda",
        "status_confirmed": "✅ tasdiqlangan",
        "status_rejected": "❌ rad etilgan",
        "contacts": "📞 Aloqa uchun: admin bilan bog'laning.",
        "lang_set": "Til o'zgartirildi.",
        "choose_category": "Qaysi yo'nalishdagi turlar kerak?",
        "cat_domestic": "🇺🇿 O'zbekiston bo'ylab",
        "cat_abroad": "✈️ Xorijga",
        "cat_pilgrimage": "🕋 Umra va Haj",
        "btn_ask": "💬 Savol berish",
        "ask_prompt": "Savolingizni yozing, AI yordamchi javob beradi. Masalan: «Dubayga 5 kunlik tur qancha?»",
        "ai_off": "Savolingiz menejerga yuborildi, tez orada javob beramiz. Turlarni ko'rish uchun menyudan foydalaning.",
        "ai_error": "Kechirasiz, hozir javob bera olmadim. Savolingiz menejerga yuborildi.",
    },
    "ru": {
        "choose_lang": "Tilni tanlang / Выберите язык / Choose a language",
        "welcome": "Здравствуйте, {name}! Выберите тур через меню или просто задайте вопрос.",
        "btn_tours": "🌍 Туры",
        "btn_my_bookings": "📋 Мои брони",
        "btn_contacts": "📞 Контакты",
        "btn_lang": "🌐 Язык",
        "btn_book": "✅ Забронировать",
        "btn_back": "⬅️ Назад",
        "btn_send_phone": "📱 Отправить номер",
        "btn_confirm": "✅ Подтвердить",
        "btn_cancel": "❌ Отмена",
        "no_tours": "Сейчас нет активных туров.",
        "tours_title": "Доступные туры:",
        "tour_card": "<b>{title}</b>\n\n{description}\n\n💵 Цена: {price} {currency}\n📅 Дата: {date}\n🪑 Свободных мест: {free}",
        "date_tbd": "по договорённости",
        "tour_not_found": "Тур не найден.",
        "no_seats": "К сожалению, свободных мест нет.",
        "ask_people": "Сколько человек поедет? (число от 1 до {max})",
        "bad_people": "Пожалуйста, введите число от 1 до {max}.",
        "ask_phone": "Отправьте номер телефона (кнопкой или в формате +998XXXXXXXXX).",
        "bad_phone": "Неверный номер. Например: +998901234567",
        "confirm_booking": "Проверьте:\n\n🌍 {title}\n👥 {people} чел.\n📱 {phone}\n💵 Итого: {total} {currency}\n\nПодтверждаете?",
        "booking_sent": "Спасибо! Заявка #{id} принята. Менеджер скоро свяжется с вами.",
        "booking_cancelled": "Бронирование отменено.",
        "booking_confirmed_user": "✅ Ваша бронь #{id} подтверждена: {title}",
        "booking_rejected_user": "❌ Ваша бронь #{id} отклонена: {title}. Если есть вопросы, свяжитесь с нами.",
        "no_bookings": "У вас пока нет броней.",
        "my_bookings_title": "Ваши брони:",
        "status_pending": "⏳ ожидает",
        "status_confirmed": "✅ подтверждена",
        "status_rejected": "❌ отклонена",
        "contacts": "📞 Для связи обратитесь к администратору.",
        "lang_set": "Язык изменён.",
        "choose_category": "Какое направление вас интересует?",
        "cat_domestic": "🇺🇿 По Узбекистану",
        "cat_abroad": "✈️ За границу",
        "cat_pilgrimage": "🕋 Умра и Хадж",
        "btn_ask": "💬 Задать вопрос",
        "ask_prompt": "Напишите вопрос, AI-помощник ответит. Например: «Сколько стоит тур в Дубай на 5 дней?»",
        "ai_off": "Ваш вопрос передан менеджеру, скоро ответим. Туры можно посмотреть через меню.",
        "ai_error": "Извините, сейчас не получилось ответить. Ваш вопрос передан менеджеру.",
    },
    "en": {
        "choose_lang": "Tilni tanlang / Выберите язык / Choose a language",
        "welcome": "Hello, {name}! Use the menu to pick a tour and book it, or just ask me a question.",
        "btn_tours": "🌍 Tours",
        "btn_my_bookings": "📋 My bookings",
        "btn_contacts": "📞 Contacts",
        "btn_lang": "🌐 Language",
        "btn_book": "✅ Book",
        "btn_back": "⬅️ Back",
        "btn_send_phone": "📱 Send phone number",
        "btn_confirm": "✅ Confirm",
        "btn_cancel": "❌ Cancel",
        "no_tours": "There are no active tours right now.",
        "tours_title": "Available tours:",
        "tour_card": "<b>{title}</b>\n\n{description}\n\n💵 Price: {price} {currency}\n📅 Date: {date}\n🪑 Free seats: {free}",
        "date_tbd": "by agreement",
        "tour_not_found": "Tour not found.",
        "no_seats": "Sorry, there are no free seats left on this tour.",
        "ask_people": "How many people are going? (a number from 1 to {max})",
        "bad_people": "Please enter a number from 1 to {max}.",
        "ask_phone": "Send your phone number (with the button or as +998XXXXXXXXX).",
        "bad_phone": "Invalid number. Example: +998901234567",
        "confirm_booking": "Please check:\n\n🌍 {title}\n👥 {people} people\n📱 {phone}\n💵 Total: {total} {currency}\n\nConfirm?",
        "booking_sent": "Thank you! Request #{id} received. A manager will contact you soon.",
        "booking_cancelled": "Booking cancelled.",
        "booking_confirmed_user": "✅ Your booking #{id} is confirmed: {title}",
        "booking_rejected_user": "❌ Your booking #{id} was declined: {title}. Contact us if you have questions.",
        "no_bookings": "You have no bookings yet.",
        "my_bookings_title": "Your bookings:",
        "status_pending": "⏳ pending",
        "status_confirmed": "✅ confirmed",
        "status_rejected": "❌ declined",
        "contacts": "📞 Please contact the administrator.",
        "lang_set": "Language changed.",
        "choose_category": "Which direction are you interested in?",
        "cat_domestic": "🇺🇿 Around Uzbekistan",
        "cat_abroad": "✈️ Abroad",
        "cat_pilgrimage": "🕋 Umrah and Hajj",
        "btn_ask": "💬 Ask a question",
        "ask_prompt": "Type your question and the AI assistant will answer. For example: \"How much is a 5-day tour to Dubai?\"",
        "ai_off": "Your question has been passed to a manager, we will reply soon. Use the menu to browse tours.",
        "ai_error": "Sorry, I couldn't answer right now. Your question has been passed to a manager.",
    },
}


def t(lang: str, key: str, **kwargs) -> str:
    text = TEXTS.get(lang, TEXTS["uz"]).get(key) or TEXTS["uz"][key]
    return text.format(**kwargs) if kwargs else text


def all_variants(key: str) -> set[str]:
    """Every translation of a button label, for matching reply-keyboard presses."""
    return {TEXTS[lang][key] for lang in LANGS}
